spring:
  application:
    name: itop_admin
  datasource:
    #    url: jdbc:mysql://192.168.187.129:3306/yb_admin_template?useUnicode=true&characterEncoding=UTF-8
    #    username: root
    #    password: root
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    hikari:
    #      # 设置是否自动提交事务，默认为true
    #      auto-commit: true
    #        # 设置用于测试连接的SQL查询语句
    #      connection-test-query: SELECT 1
    #      # 设置获取数据库连接的超时时间，默认为30秒，单位是秒
    #      connection-timeout: 30000
    #      # 设置连接在连接池中保持空闲的最长时间，默认为10分钟，单位是秒
    #      idle-timeout: 30000
    #      # 设置连接在连接池中允许存在的最长时间，默认为30分钟，单位是秒
    #      max-lifetime: 1800000
    #      # 设置连接池中允许的最大连接数，默认为10
    #      maximum-pool-size: 15
    #      # 设置连接池中保持的最小空闲连接数，默认为10
    #      minimum-idle: 5
    #      # 设置连接池的名称，默认为"HikariPool-1"
    #      pool-name: itop_HikariPool
      url: jdbc:h2:mem:test
      #配置JDBC Driver
      driver-class-name: org.h2.Driver
      #配置数据库用户名
      username: root
      #配置数据库密码
      password: 123456
      #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
      h2:
        console:
          enabled: true
          #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。默认为/h2-console
          path: /h2
          # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
          settings:
            web-allow-others: true

server:
  port: 17701


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

