server:
  port: 8731
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.187.129:3306/yb_admin?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: root



logging:
  level:
    org.springframework.security: TRACE


